# Generated by Django 6.0.7 on 2026-07-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="data_joined",
            new_name="date_joined",
        ),
    ]
