# Generated by Django 6.0.7 on 2026-08-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payments_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID сессии",
                max_length=100,
                null=True,
                verbose_name="ID сессии",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="status",
            field=models.CharField(
                blank=True,
                default="pending",
                max_length=100,
                null=True,
                verbose_name="Статус платежа",
            ),
        ),
    ]
