# Generated by Django 6.0.7 on 2026-08-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payments_session_id_payments_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="session_id",
        ),
        migrations.AddField(
            model_name="payments",
            name="payment_url",
            field=models.TextField(
                blank=True,
                help_text="Прямая ссылка на платежную страницу Stripe Checkout",
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор стоимости продукта в системе Stripe",
                max_length=255,
                null=True,
                verbose_name="Stripe ID Цены",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_product_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор созданного продукта в системе Stripe",
                max_length=255,
                null=True,
                verbose_name="Stripe ID Продукта",
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор сессии оплаты Stripe Checkout",
                max_length=255,
                null=True,
                verbose_name="Stripe ID Сессии",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer_to_account", "Перевод на счет"),
                    ("stripe", "Онлайн-оплата (Stripe)"),
                ],
                help_text="Выберите способ оплаты",
                max_length=50,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("succeeded", "Оплачено"),
                    ("failed", "Ошибка платежа"),
                ],
                default="pending",
                max_length=100,
                verbose_name="Статус платежа",
            ),
        ),
    ]
