# Generated by Django 6.0.7 on 2026-08-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aurora", "0005_alter_course_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Время последнего обновления"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Время последнего обновления"
            ),
        ),
    ]
