# Generated by Django 6.0.7 on 2026-08-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aurora", "0006_course_updated_at_lesson_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="notification_sent",
            field=models.BooleanField(default=False),
        ),
    ]
